apiVersion: v1
kind: Pod
metadata:
  name: pod-a3-pending
  namespace: troubleshooting-lab
  labels:
    scenario: a3
spec:
  containers:
    - name: app
      image: nginx:1.27-alpine
      resources:
        requests:
          cpu: 50m
          memory: 32Mi
        limits:
          cpu: 200m
          memory: 128Mi
