apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: lab5
data:
  nginx.conf: |
    events {}
    http {
        server {
            listen 80;
            location / {
                root /usr/share/nginx/html;
                index index.html;
            }
            location /health {
                return 200 'OK';
                add_header Content-Type text/plain;
            }
        }
    }
  index.html: |
    <!DOCTYPE html>
    <html lang="es">
    <head>
      <meta charset="UTF-8">
      <title>Kubernetes ConfigMap</title>
    </head>
    <body>
      <h1>Configuración desde ConfigMap</h1>
      <p>Contenido externalizado correctamente.</p>
    </body>
    </html>