apiVersion: v1
kind: Pod
metadata:
  name: secret-demo-pod
  namespace: lab5
spec:
  containers:
    - name: app
      image: busybox:1.36
      command:
        - sh
        - -c
        - |
          echo "DB_USER=$DB_USER"
          echo "DB_HOST=$DB_HOST"

          if [ -n "$DB_PASSWORD" ]; then
            echo "DB_PASSWORD definida correctamente"
          else
            echo "ERROR: DB_PASSWORD no fue inyectada"
          fi

          FILE_DB_USER="$(cat /etc/db-secret/db-user)"
          printf 'Archivo DB_USER=%s\n' "$FILE_DB_USER"

          sleep 3600
      envFrom:
        - secretRef:
            name: db-credentials
      volumeMounts:
        - name: db-secret-volume
          mountPath: /etc/db-secret
          readOnly: true
  volumes:
    - name: db-secret-volume
      secret:
        secretName: db-credentials
        items:
          - key: DB_USER
            path: db-user
  restartPolicy: Never