apiVersion: v1
kind: Pod
metadata:
  name: rbac-demo-pod
  namespace: lab5
spec:
  serviceAccountName: app-reader
  containers:
    - name: kubectl
      image: bitnami/kubectl:latest
      command:
        - sh
        - -c
        - |
          echo "=== ServiceAccount ==="
          ls /var/run/secrets/kubernetes.io/serviceaccount/

          echo ""
          echo "=== Pods permitidos ==="
          kubectl get pods -n lab5

          echo ""
          echo "=== ConfigMaps permitidos ==="
          kubectl get configmaps -n lab5

          echo ""
          echo "=== Secrets denegados ==="
          kubectl get secrets -n lab5 || true

          sleep 3600